name: Docker build && publish

on:
  workflow_call:
    inputs:
      imageName:
        type: string
        description: 'Name of the Image pushed to registry'
        required: true
      imageTag:
        type: string
        description: 'Tag of the Image pushed to registry'
      module_name:
        type: string
        description: 'Tag of the Image pushed to registry'

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Lint Dockerfile
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile
        working-directory: ${{ inputs.module_name }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Prepare Package Name
        run: |   
          IMAGE_NAME=$(echo ${{ inputs.imageName }} | tr '[:upper:]' '[:lower:]')
          if [ -n "${{ inputs.imageTag }}" ]; then
            TAG=":${{ inputs.imageTag }}"
          else
            TAG=""
          fi
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/github-edp/${{ env.IMAGE_NAME }}:${{ github.sha }}
          

      - name: Push Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/github-edp/${{ env.IMAGE_NAME }}${{ env.TAG }}